### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by BartNetJS** [Dealogic/webpack-vsts-extension#25] opened 2017-05-17 10:37 UTC
I've got above error message when i run webpack in vsts ci:

The app is generated with dotnet cli:
dotnet new angular

I think it is an issue in webpack.config.vendor.js, but I'm not sure.

this is the log extract:

2017-05-17T10:17:47.1939618Z ##[section]Starting: webpack
2017-05-17T10:17:47.1949620Z ==============================================================================
2017-05-17T10:17:47.1949620Z Task         : webpack
2017-05-17T10:17:47.1949620Z Description  : bundle your assets, scripts, images, styles
2017-05-17T10:17:47.1949620Z Version      : 2.0.2
2017-05-17T10:17:47.1949620Z Author       : Dealogic
2017-05-17T10:17:47.1949620Z Help         : [More information](https://marketplace.visualstudio.com/items?itemName=Dealogic.webpack-vsts-extension) [webpack](https://webpack.github.io/)
2017-05-17T10:17:47.1949620Z ==============================================================================
2017-05-17T10:17:47.3889694Z webpack
2017-05-17T10:17:47.3899695Z building the webpack project
2017-05-17T10:17:47.3909696Z executing the command: node "d:\a\1\s\node_modules\webpack\bin\webpack.js" --json --config webpack.config.vendor.js --verbose --display-error-details
2017-05-17T10:17:59.3096545Z webpack succeeded
2017-05-17T10:17:59.3096545Z creating the summary section
2017-05-17T10:17:59.3156548Z ##[error]webpack failed
2017-05-17T10:17:59.3186538Z ##[error]TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
2017-05-17T10:17:59.3186538Z [TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined]
2017-05-17T10:17:59.3216533Z ##[section]Finishing: webpack

this is the webpack.config.vendor.js

`const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const merge = require('webpack-merge');

module.exports = (env) => {
    const extractCSS = new ExtractTextPlugin('vendor.css');
    const isDevBuild = !(env && env.prod);
    const sharedConfig = {
        stats: { modules: false },
        resolve: { extensions: [ '.js' ] },
        module: {
            rules: [
                { test: /\.(png|woff|woff2|eot|ttf|svg)(\?|$)/, use: 'url-loader?limit=100000' }
            ]
        },
        entry: {
            vendor: [
                '@angular/common',
                '@angular/compiler',
                '@angular/core',
                '@angular/http',
                '@angular/platform-browser',
                '@angular/platform-browser-dynamic',
                '@angular/router',
                '@angular/platform-server',
                'angular2-universal',
                'angular2-universal-polyfills',
                'bootstrap',
                'bootstrap/dist/css/bootstrap.css',
                'es6-shim',
                'es6-promise',
                'event-source-polyfill',
                'jquery',
                'zone.js',
            ]
        },
        output: {
            publicPath: '/dist/',
            filename: '[name].js',
            library: '[name]_[hash]'
        },
        plugins: [
            new webpack.ProvidePlugin({ $: 'jquery', jQuery: 'jquery' }), // Maps these identifiers to the jQuery package (because Bootstrap expects it to be a global variable)
            new webpack.ContextReplacementPlugin(/\@angular\b.*\b(bundles|linker)/, path.join(__dirname, './ClientApp')), // Workaround for https://github.com/angular/angular/issues/11580
            new webpack.IgnorePlugin(/^vertx$/) // Workaround for https://github.com/stefanpenner/es6-promise/issues/100
        ]
    };

    const clientBundleConfig = merge(sharedConfig, {
        output: { path: path.join(__dirname, 'wwwroot', 'dist') },
        module: {
            rules: [
                { test: /\.css(\?|$)/, use: extractCSS.extract({ use: isDevBuild ? 'css-loader' : 'css-loader?minimize' }) }
            ]
        },
        plugins: [
            extractCSS,
            new webpack.DllPlugin({
                path: path.join(__dirname, 'wwwroot', 'dist', '[name]-manifest.json'),
                name: '[name]_[hash]'
            })
        ].concat(isDevBuild ? [] : [
            new webpack.optimize.UglifyJsPlugin()
        ])
    });

    const serverBundleConfig = merge(sharedConfig, {
        target: 'node',
        resolve: { mainFields: ['main'] },
        output: {
            path: path.join(__dirname, 'ClientApp', 'dist'),
            libraryTarget: 'commonjs2',
        },
        module: {
            rules: [ { test: /\.css(\?|$)/, use: ['to-string-loader', isDevBuild ? 'css-loader' : 'css-loader?minimize' ] } ]
        },
        entry: { vendor: ['aspnet-prerendering'] },
        plugins: [
            new webpack.DllPlugin({
                path: path.join(__dirname, 'ClientApp', 'dist', '[name]-manifest.json'),
                name: '[name]_[hash]'
            })
        ]
    });

    return [clientBundleConfig, serverBundleConfig];
}
`

**Comment by jkanczler** [comment] 2017-05-17 11:34
According to the log webpack task is failing when it's trying to create the webpack summary section onto the build summary page.

```
2017-05-17T10:17:59.3096545Z creating the summary section
2017-05-17T10:17:59.3156548Z ##[error]webpack failed
2017-05-17T10:17:59.3186538Z ##[error]TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
```

As I can see you passed the following arguments: --config webpack.config.vendor.js --verbose --display-error-details.

```
2017-05-17T10:17:47.3909696Z executing the command: node "d:\a\1\s\node_modules\webpack\bin\webpack.js" --json --config webpack.config.vendor.js --verbose --display-error-details
```

Could you try to remove the --verbose --display-error-details flags?

If those won't help you, then is it possible to send the json content for us? Run the following command locally:

```
webpack --json --config webpack.config.vendor.js --verbose --display-error-details > result.json
```

**Comment by BartNetJS** [comment] 2017-05-17 13:09
I added the --display-error-details to have more details about the error. So it is the same without
Hereby the local log file (compiling fine)

[result.zip](https://github.com/Dealogic/webpack-vsts-extension/files/1007649/result.zip)

**Comment by jkanczler** [comment] 2017-05-17 13:42
Thank you very much. It was a great help to understand what the problem is. It seems we don't support all the scenarios. In the attached result.json file there's no assets array, but instead a children array with two objects. Each object with its own errors, warnings and assets array. I suppose it's because of the dll library build. I'm trying to find out how we can support your scenario correctly.

**Comment by jkanczler** [comment] 2017-05-17 14:08
I'm thinking on a hot fix for version 2 either, to support your scenario, but it can happen that this will be supported in 3.0, related to the following issue: [#26 VSTS build task should rely on the webpack node.js api].

**Comment by jkanczler** [comment] 2017-05-18 09:53
To provide a hot fix for this. Could you send the result of the following:

```
webpack --config webpack.config.vendor.js --verbose --display-error-details > result.txt
```

I would like to understand how the console output should look like in case of this scenario.

**Comment by BartNetJS** [comment] 2017-05-22 09:58
@jkanczler the zip was already included in my previous response

**Comment by jkanczler** [comment] 2017-05-22 10:02
I need a new one without the json flag.

**Closed as completed** 2017-05-22 21:15 UTC
Labels: bug

**Comment by BartNetJS** [comment] 2017-05-23 08:37
@jkanczler hereby the file
[result.zip](https://github.com/Dealogic/webpack-vsts-extension/files/1021446/result.zip)
